name: todo
publish_to: none

# dart pub global activate derry
scripts:
  runner_build: flutter packages pub run build_runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.17.0"

dependencies:
  flex_color_scheme: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: any
  reactive_forms: any
  realm: any
  styled_widget: any

dev_dependencies:
  build_runner: any
  very_good_analysis: any
